config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'
  resources :users, except: [:index]


  get "/login", to: "sessions#new"
  get "/logout", to: "sessions#destroy"
  post "/sessions", to: "sessions#create"

  resources :posts

  resources :cities

  resources :comments, except: [:post]

  post "/posts/:id/comments", to: "comments#create"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :posts
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :Post, optional: true
  belongs_to :User, optional: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :City, optional: true
  belongs_to :User, optional: true
  has_many :comments, dependent: :destroy

  validates :title, presence: true, length: {maximum: 200, minimum: 1}
  validates :message, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :posts
  has_many :comments
  validates :email, uniqueness: true
  validates :name, :email, :current_city, :password, presence: true

  def self.confirm(params)
    @user = User.find_by({email: params[:email]})
    @user ? @user.authenticate(params[:password]) : false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper

end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def show
    @city = City.find_by_id(params[:id])
    last_city(@city)
    @posts = @city.posts
    @posts = @posts.order(created_at: :desc)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :user_match?, only: [:destroy]
  before_action :require_login, expect: [:index, :show]

  def index
  end

  def show
  end

  def create
    @comment = Comment.create(comment_params)
    Post.find_by_id(params[:id]).comments << @comment
    @post.comments << @comment
    User.find_by_id(session[:user_id]).comments << @comment
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find_by_id(@comment.post_id)
    @comment.destroy
    redirect_to post_path(@post)
  end

  private
  def comment_params
    params.require(:comment).permit(:message)
  end

  def user_match?
    @comment = Comment.find_by_id(params[:id])
    if session[:user_id] != @comment.user_id
      redirect_to root_path
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login, except: [:show, :new]
  before_action :user_match?, only: [:edit, :update, :destroy]

  def show
    @post = Post.find_by_id(params[:id])
    @user = User.find_by_id(@post.user_id)
    @comments = @post.comments
    @new_comment = Comment.new
  end

  def new
    if session[:user_id].nil?
      flash[:error] = "You must be logged in to leave a post"
      redirect_to city_path(session[:last_city_id])
    else
      @post = Post.new
    end
  end

  def create
    @post = Post.create(post_params)
    if @post.valid?
      User.find_by_id(session[:user_id]).posts << @post
      @city = City.find_by_id(session[:last_city_id])
      @city.posts << @post
      redirect_to city_path(@city)
    else
      flash[:error] = "#{@post.errors.full_messages.join(", ")}"
      redirect_to new_post_path
    end
  end

  def edit
    @user = User.find_by_id(session[:user_id])
  end

  def update
    @post.update(post_params)
    redirect_to post_path(@post)
  end

  def destroy
    @post.destroy
    redirect_to user_path(session[:user_id])
  end

  private
  def post_params
    params.require(:post).permit(:title, :message)
  end

  def user_match?
    @post = Post.find_by_id(params[:id])
    if session[:user_id] != @post.user_id
      redirect_to root_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user_params = params.require(:user).permit(:email, :password)
      @user = User.confirm(user_params)
      if @user
       login(@user)
       redirect_to user_path(@user)
      else
       flash[:error] = "Incorrect email or password."
       redirect_to login_path
      end
  end

  def destroy
    logout
    redirect_to root_path
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: [:show, :edit, :update]


  def index
    @cities = City.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.valid?
      login(@user)
      redirect_to @user
    else
      flash[:error] = "#{@user.errors.full_messages.join(", ")}"
      redirect_to new_user_path
    end
  end

  def show
    @user = User.find_by_id(params[:id])
    @posts = @user.posts
    @cities = City.all
  end

  def edit
    @user = User.find_by_id(session[:user_id])
  end

  def update
    @user = User.find_by_id(session[:user_id])
    @user.update(user_params)
    @user.save(validate: false)
    redirect_to user_path(@user.id)
  end

  # private

  def user_params
    params.require(:user).permit(:name, :current_city, :image, :email, :password)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login(user)
    session[:user_id] = user.id
    @current_user = user
  end

  def last_city(city)
    session[:last_city_id] = city.id
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def logout
    @current_user = session[:user_id] = nil
  end

  def require_login
    redirect_to root_path and return if session[:user_id].nil?
  end

  def get_path_from_city(city)
    "/cities/#{city.id}"
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cities/show.html.erb
<div class="header z-depth-1">
  <img src= "<%= @city.image %>" >
  <span class="city_name z-depth-1">
    <h3 class="city_title"><%= @city.name %></h3>
  </span>
</div>

<div class="post_background">
  <button class="btn waves-effect waves-light new-post"><%= link_to "Add New Post", new_post_path %></button>
  <% flash.each do |name, msg| %>
    <p class="new-post-error">
     <%= name.capitalize %>: <%= msg %>
    </p>
  <% end %>
  <div class="post_wrap">
    <% if @city.posts.count == 0 %>
      <br>
      <div class="contain"><div class="divider"></div></div>
      <h5> Sample Post </h5>
      <p> This is the template showing how your post will be appear on the page. Log in to create a new post. </p>
      <p> Junket! </p>
      <span>
        <small class="right-align">Post on Sep. 25, 2017</small>
      </span>
      <br>
      <p> 0 Comments <p>
      <div class="divider"></div>
    <% else %>
      <%  @posts.each do |post| %>
        <% @user = User.find_by_id(post.user_id) %>
        <br>
        <div class="contain"><div class="divider"></div></div>
        <h5> <%= link_to "#{post.title}", post_path(post), class: "post_link" %> </h5>
        <p> <%= post.message%> </p>
        <% if session[:user_id].nil? %>
          <p><%= @user.name %></p>
        <% else %>
          <%= link_to "#{@user.name}", user_path(@user), class: "body_link" %>
        <% end %>
        <span>
          <small class="right-align"><%= post.created_at.strftime("Posted on %b %-d, %Y")%></small>
        </span>
        <br>
        <p> <%= pluralize(post.comments.count, 'Comment') %> <p>
        <% if post.comments.count > 0 %>
          <%= link_to "Go to Thread", post_path(post), class: "body_link" %>
        <% else %>
          <%= link_to "Add a Comment", post_path(post), class: "body_link" %>
        <% end %>
      <div class="divider"></div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vagabond</title>
    <link href="/assets/world.png" rel="shortcut icon" type="image/x-icon" />
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <ul id="dropdown1" class="dropdown-content">
    <% City.all.each do |city| %>
      <li><%= link_to city.name, city_path(city.id) %></li>
      <li class="divider"></div>
    <% end %>
    </ul>
    <nav>
      <% if session[:user_id].nil? %>
       <div class="nav-wrapper">
         <a href= "/" class="brand-logo junket">Junket!</a>
         <ul id="nav-mobile" class="right hide-on-med-and-down">
           <li><a class="dropdown-button" href="#!" data-activates="dropdown1">Cities</a></li>
           <li><%= link_to "Sign Up", new_user_path %></li>
           <li><%= link_to "Log In", login_path%></li>
         </ul>
       </div>
      <% else %>
        <div class="nav-wrapper">
          <a href="/" class="brand-logo junket">Junket!</a>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><a class="dropdown-button" href="#!" data-activates="dropdown1">Cities</a></li>
            <li><%= link_to "Profile", user_path(session[:user_id]) %></li>
            <li><%= link_to "Log Out", logout_path%></li>
          </ul>
        </div>
      <% end %>
     </nav>

    <%= yield %>
  </body>
</html>

app/views/posts/_logged_in_posts.html.erb
  <p>Posted by <%= link_to "#{@user.name}", user_path(@user), class: "body_link" %> <%= @post.created_at.strftime(" on %b %-d, %Y")%></p>

<p>Comments:</p>

<div class="comments-thread">
    <% @comments.each do |comment| %>
      <% commenter = User.find_by_id(comment.user_id) %>
      <big><%= comment.message %></big>

        <span>
          <p><%= link_to "#{commenter.name}", user_path(commenter), class: "body_link" %> <%= comment.created_at.strftime(" on %b %-d, %Y")%></p>
        </span>

      <% if session[:user_id] == commenter.id %>
        <%= link_to material_icon.delete, comment, :url => "/comments/#{comment.id}", method: :delete, class: "body_link" %>
      <% end %>

      <br>

    <% end %>

  <%= form_for @new_comment, :url => "/posts/#{@post.id}/comments" do |f| %>

    <div>
      <%= f.text_area :message, placeholder: "Add New Comment" %>
    </div>

      <%= f.submit class: "btn waves-effect waves-light"%>

  <% end %>
</div>

app/views/posts/edit.html.erb
<div class="post_body page_body container">
  <h1>Edit Post</h1>

  <%= form_for @post do |f| %>

    <div>
      <%= f.text_field :title, placeholder: "Title" %>
    </div>
    <div>
      <%= f.text_area :message, placeholder: "Message" %>
    </div>
    <%= f.submit class: "btn waves-effect waves-light" %>
  <% end %>
  <br>
  <%= link_to material_icon.arrow_back, user_path(@user) %>

</div>

app/views/posts/new.html.erb
<div class="page_body container">
  <h1>Create a New Post</h1>
  <% flash.each do |name, msg| %>
   <p>
     <%= name.capitalize %>: <%= msg %>
   </p>
   <% end %>
  <%= form_for @post do |f| %>
    <div>
      <%= f.text_field :title, placeholder: "Title" %>
    </div>
    <div>
      <%= f.text_area :message, placeholder: "Message", class: "text_box" %>
    </div>
    <%= f.submit class: "btn waves-effect waves-light" %>
  <% end %>
  <br>
  <% @city = City.find_by_id(session[:last_city_id]) %>
  <%= link_to material_icon.arrow_back, city_path(@city) %>
</div>

app/views/posts/show.html.erb
<div class="page_body container">
  <h2><%= @post.title %></h2>
  <% @city = City.find_by_id(@post.city_id) %>
  <h4><%= @post.message %></h4>
  <big>City: <%= link_to "#{@city.name}", city_path(@city), class: "body_link" %></big>

  <% if session[:user_id].nil? %>
    <p>Posted by <%= @user.name %> <%= @post.created_at.strftime(" on %b %-d, %Y")%></p>

      <p>Comments:</p>

      <div class="comments-thread">
          <% @comments.each do |comment| %>
            <% commenter = User.find_by_id(comment.user_id) %>
            <big><%= comment.message %></big>
              <span>
                <p><%= commenter.name %> <%= comment.created_at.strftime(" on %b %-d, %Y")%></p>
              </span>
            <br>
        <% end %>
      </div>

  <% else %>
   <%= render 'logged_in_posts' %>
  <% end %>

</div>

app/views/users/edit.html.erb
<div class="page_body container">
  <h1> Edit User </h1>
  <hr>
  <%= form_for @user do |f| %>
    <div>
      <%= f.text_field :name, placeholder: 'Name' %>
    </div>
    <div>
      <%= f.text_field :current_city, placeholder: 'Current City' %>
    </div>
    <div>
      <%= f.text_field :image, placeholder: 'Profile Picture URL' %>
    </div>

    <%= f.submit 'Save Changes', class: "btn waves-effect waves-light" %>
  <% end %>
  <br>
  <%= link_to material_icon.arrow_back, user_path(@user) %>

</div>

app/views/users/index.html.erb
<div class="header_hp center-align">
  <%=image_tag("arch-background.jpg")%>

</div>

<h4 class="center-align">Explore These Cities</h4>
<br>
<div class="divider"></div>
<br>
<div class="row">
  <% @cities.each do |city| %>
<a href='<%= get_path_from_city(city) %>'>
  <div class="col l4 m6 s12">
    <div class="card">
      <div class="real-card">
        <div class="card-image">
          <img class="city_picture container" src="<%=city.image %>">
        </div>
        <span class="card-title card_title"><%= city.name %></span>
      </div>
    </div>
  </div>
  <% end %>
</div>
<br>
<br>

app/views/users/new.html.erb
<div class="page_body container">
  <h1> Create User </h1>
  <% flash.each do |name, msg| %>
   <p>
     <%= name.capitalize %>: <%= msg %>
   </p>
 <% end %>
  <%= form_for @user do |f| %>
    <div>
      <%= f.text_field :name, placeholder: 'Name' %>
    </div>
    <div>
      <%= f.text_field :current_city, placeholder: 'Current City' %>
    </div>
    <div>
      <%= f.text_field :image, placeholder: 'Profile Picture Url (Optional)' %>
    </div>
    <div>
      <%= f.email_field :email, placeholder: 'Email Address' %>
    </div>
    <div>
      <%= f.password_field :password, placeholder: 'Password' %>
    </div>
    <%= f.submit 'Sign Up', class: "btn waves-effect waves-light" %>
  <% end %>
  <br>
  <%= link_to material_icon.arrow_back, root_path %>
</div>

app/views/users/show.html.erb
<div class="row page_body">
  <div class="z-depth-3 user_info left">
    <div class="container info_wrap">
      <div class="image_wrap">
        <% if @user.image == "" %>
          <img class="user_pic" src="https://maxcdn.icons8.com/Share/icon/Users//user_male_circle_filled1600.png">
        <% else %>
          <img class="user_pic" src="<%= @user.image %>" >
        <% end %>
      </div>
      <h4 class="center-align"> <%= @user.name %> </h4>
        <div class="divider"></div>
      <div class="center-align">
        <p class="left-align p_weight"> <%= @user.created_at.strftime("Member since %b %-d, %Y") %> </p>
        <p class="left-align p_weight"> Currently in <%= @user.current_city %> </p>
        <p class="left-align p_weight"> <%= pluralize(@user.comments.count, 'Comment') %> </p>
        <% if session[:user_id] == @user.id %>
          <br>
          <%= link_to 'Edit Profile', edit_user_path(@user), class: "body_link btn edit-user" %>
        <% end %>
      </div>
    </div>
  </div>
  <h4> Posts </h4>
  <div class="divider"></div>
  <div class="tips_wrap left">
    <% if @user.posts.length == 0 %>
      <p> To create a post, check out these cities: </p>
      <ul>
        <% @cities.each do |city| %>
          <li class="city_choice"> <%= link_to city.name, city_path(city), class: "city_link" %> </li>
        <% end %>
      </ul>
    <% else %>
      <% @posts.each do |post| %>
        <h5> <%= link_to post.title, post_path(post), class: "post_link" %> </h5>
        <p> <%= post.message%> </p>
        <span>
          <small class="right-align"><%= post.created_at.strftime("Posted on %b %-d, %Y")%></small>
        </span>
        <br>
        <% if session[:user_id] == @user.id %>
          <%= link_to material_icon.delete, post, method: :delete, data: { confirm: 'Are you sure?' }, class: "body_link" %>
          <%= link_to material_icon.edit, edit_post_path(post), class: "body_link" %>
        <% end %>

        <div class="divider"></div>
      <% end %>
    <% end %>
  </div>
</div>